"""add review

Revision ID: 0c256dbf5561
Revises: 2cc9cd0b5afc
Create Date: 2026-04-30 10:34:24.967725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c256dbf5561'
down_revision: Union[str, Sequence[str], None] = '2cc9cd0b5afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('book_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('books_user_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_user_id_fkey'), 'books', 'users', ['user_id'], ['uid'])
    op.drop_column('books', 'user_uid')
    op.drop_table('reviews')
    # ### end Alembic commands ###
